"""
Interactive CLI:
- Reads lines from stdin.
- A *blank* line ends the session and prints "Break time!".
- For non-blank lines:
    - parse -> dispatch -> print returned logs
    - For RUN: after EACH TURN, the CLI should print the display.
      To keep tests simple, the Scheduler.run() should return *all* logs
      for all turns in order; the CLI prints them as-is.
      The display for each turn should be generated by Scheduler.display().

This file intentionally avoids implementing the project logic; that belongs in scheduler.py.
"""

import sys
from typing import List
from parser import parse_command
from scheduler import Scheduler


def main() -> None:
    sched = Scheduler()

    for raw in sys.stdin:
        line = raw.rstrip("\n")

        # Blank line ends session
        if line == "":
            print("Break time!")
            return

        parsed = parse_command(line)
        logs: List[str] = []

        if parsed is None:
            # comment or whitespace line inside session (ignored)
            pass
        else:
            cmd, args = parsed

            # Dispatch with minimal argument plumbing.
            try:
                if cmd == "CREATE":
                    if len(args) != 2:
                        logs.extend([f"time=? event=error reason=bad_args"])
                    else:
                        qid, cap_str = args
                        cap = int(cap_str)
                        logs.extend(sched.create_queue(qid, cap))

                elif cmd == "ENQ":
                    if len(args) != 2:
                        logs.extend([f"time=? event=error reason=bad_args"])
                    else:
                        qid, item = args
                        logs.extend(sched.enqueue(qid, item))

                elif cmd == "SKIP":
                    if len(args) != 1:
                        logs.extend([f"time=? event=error reason=bad_args"])
                    else:
                        (qid,) = args
                        logs.extend(sched.mark_skip(qid))

                elif cmd == "RUN":
                    if not (1 <= len(args) <= 2):
                        logs.extend([f"time=? event=error reason=bad_args"])
                    else:
                        quantum = int(args[0])
                        steps = int(args[1]) if len(args) == 2 else None
                        # Expect Scheduler.run to return *all* logs in order.
                        logs.extend(sched.run(quantum, steps))

                else:
                    logs.extend([f"time=? event=error reason=unknown_command"])

            except ValueError:
                # e.g., non-integer capacity/quantum/steps
                logs.extend([f"time=? event=error reason=bad_args"])

        # Print logs produced by this line
        if logs:
            print("\n".join(logs))


if __name__ == "__main__":
    main()
